### ISSUE TITLE
Unable to load library 'discord-rpc':

### ISSUE THREAD

**Issue by Speedyyz** [MinnDevelopment/java-discord-rpc#31]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  RenderPlayerAPIPlugin (RenderPlayerAPI-1.10.2-1.1.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 14/09/18 21:32
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from AlbianRPCMod (albianrpcmod)
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc': Le module spécifié est introuvable.

	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:169)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:242)
	at com.sun.jna.Library$Handler.<init>(Library.java:140)
	at com.sun.jna.Native.loadLibrary(Native.java:368)
	at com.sun.jna.Native.loadLibrary(Native.java:353)
	at club.minnced.discord.rpc.DiscordRPC.<clinit>(DiscordRPC.java:42)
	at fr.speedyy.albianrpcmod.AlbianRPCMod.preInit(AlbianRPCMod.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 429580728 bytes (409 MB) / 738197504 bytes (704 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_E3 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCH	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCH	RenderPlayerAPI{1.1} [Render Player API] (minecraft.jar) 
	UCH	albianonline{@VERSION@} [Albian Online] (AlbianOnlineMod-Low.jar) 
	UCE	albianrpcmod{1.0} [AlbianRPCMod] (albianrpcmod-1.0-all.jar) 
	UCH	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.10.2.jar) 
	UCH	ctm{MC1.10.2-0.2.3.26} [CTM] (CTM-MC1.10.2-0.2.3.26.jar) 
	UCH	chisel{MC1.10.2-0.1.1.39} [Chisel] (Chisel-MC1.10.2-0.1.1.39.jar) 
	UCH	gvc{0.6.1} [§aGliby's§f Voice Chat Mod] (GlibysVC-Client-1.10.2.jar) 
	UCH	hidenames{1.3} [HideNames] (HideNames-1.3.jar) 
	UCH	thutcore{3.19.1} [Thut Core] (thutcore-3.19.1.jar) 
	UCH	thuttech{@VERSION@} [Thut's Tech] (thuttech-4.0.10.b.jar) 
	Loaded coremods (and transformers): 
RenderPlayerAPIPlugin (RenderPlayerAPI-1.10.2-1.1.jar)
  api.player.forge.RenderPlayerAPITransformer
CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GT 705/PCIe/SSE2'
	OptiFine Version: OptiFine_1.10.2_HD_U_E3
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.35
	OpenGlRenderer: GeForce GT 705/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

Can you help me please, im stuck  few days ago, i'am french so can you speak as clearly as possible please

**Comment by kkirigaya** [comment]
Hi there! Is this a Minecraft mod that you created, or did you find this online? If this is yours, please provide a link to your source code. If this isn't, please tel us where you downloaded this mod. This crash log alone cannot help you, so we need more information. :)

**Comment by Speedyyz** [comment]
Hi thanks for your answer, no this is my Minecraft Mod there's my build.gradle file : https://pastebin.com/uaHTh79F
